name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}

  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --quiet
      - run: npm ci
      - id: date
        run: echo "date=$(TZ=America/Los_Angeles date +'%Y-%U')" >> $GITHUB_OUTPUT
      - id: cache-data
        uses: actions/cache@v4
        with:
          path: src/.observablehq/cache
          key: data-${{ hashFiles('src/data/*') }}-${{ steps.date.outputs.date }}

      - run: poetry run npm run build
      - run: env | grep OBSERVABLE
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}
      - run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}